language: r
sudo: false
cache: packages
r_packages:
- knitr
- covr
- drat
after_success:
- Rscript -e 'library("covr");codecov()'
- test $TRAVIS_PULL_REQUEST == "false" && test $TRAVIS_BRANCH == "master" && bash
  drat.sh
env:
  global:
  - secure: GTRaJS+rNBDy8NkPvL47ey9XXkTWHPzTWvME8NofUjJWqcF2XynHlswE+U0N4rpO1NMjGbKBFDXblgJTQ8V5NiT9vORWTjKKhIMGVvKrsV95Wgl9tjLQj+1/Ughb3UU3OYvyHJXRxuiFzxrEfMdAJSnkvX7n1rWBbd1VJDgbFoBGmopY+Iq/wSo/ZIjhRuDR19tiB7C1OrOtVbd0Kzx0cSjCM/bZce40AXRuOerntblJExqTb9F9CGu4cfFfxamsThSnED+z8R6HKUlrwYb3us40vIea8O8Sh3TavTLU0hKQn1ZldzxqbUMUGKrbhcf+iwd2lt6RC9DvNdIqnI2HzeCw8nWZMUh4lS3GmTVFwiHY3BF+YrXPkRGwAh1JN2b5GsBeCgiSJwjBgOmBYJKPDiHsWZWuScxXEbe4L2xWsa9m1spkkTYTNraJlRicVwTaCeY/ObmH81s2SdaIwa9oGoZ4TuKZm30/c5JkD7tEcU+9P6xtcmT8/fEFy6Z8pVTPcrK77gesDl/nEJI65/8FVzRo1/+OevgNH4fcTdmuLNqpVL9a7U1AluxUJGGF2kwPSLbdISYY/DACykzN1e4SYGc0Lj+Gi5euFp8nPXrUh/5aaVoXy7cUH0wp4fGyIVlbygg864MUQWeuLxfJLqPevHrBj0ZGJKa0c0LVrNA6ywE=
  - secure: cFRr8YqYRGq3YNUOr6ULHgjqnMiLWQ34P19nV0XjRxw/Ww8hZOcoKm3wvKBDw0T0/Qh91tIQnfO8NSjWMlGBT9Ae7pOc4fwSuJL1PPtCq+UZlMoVhxNIWhS/ZZowa9GmuY84EJc+95lOnMczjll2tMIH+EdOLDMitDkVwNC7OGrWhVZpi0ggRkbgUL8QZIFSDOQFte7S5nuX6b721Ux7khNbR+mHG5lI+nIkzRZotC/uRKuhLaAEAF5CXZqdSbckC+6Rd043zKFiMInWj8OHp8S++MjnNacXbz5O+8mcaRD8cRCUaPm19B1YeD13625TfTh0pHZSMObA4UvvGxyBMwfTpbMJ49rtvLF+owU0b224fX8lt9NCv/QVT9KlX6rFdvr79VV98SxM8NkYrn9LFyuGZ6g/ZTTRqy2DZSnIA6qZ1fJjR4cv4UyFqcZShI2Iiho0Uz3O9zJsUpAFrOMWp6GqOsNDSt9pBEVcKEgPQJJqOClCciUrB8v0t9IuTz3OebfvH8H1ICD0bfne13gKNRqAlljSBk3S3teaMsL5QdZZtCqAkqbLBTixCRLwXyfHSZxJoxb3pYgb71mPAnoBXvnLt71eVi2xbVX1jKepny6XX/vmQuC/DlwUn3uT99Nu3mp1QGBeKKedT2giqCvuHyNORfN8rze0h4k629CxEys=
before_install:
- openssl aes-256-cbc -K $encrypted_d4ad93fbc68d_key -iv $encrypted_d4ad93fbc68d_iv
  -in auth.json.enc -out auth.json -d
