language: r
cache: packages
notifications:
  slack: edmondsons:kgTokxui4ZzTsqdD19tCoozf
  email:
    on_success: change
    on_failure: change
r_packages:
- knitr
- covr
- drat
after_success:
- Rscript -e 'library("covr");codecov()'
- test $TRAVIS_PULL_REQUEST == "false" && test $TRAVIS_BRANCH == "master" && bash
  drat.sh
before_install:
- openssl aes-256-cbc -K $encrypted_fdd803ee6427_key -iv $encrypted_fdd803ee6427_iv
  -in tests/testthat/auth.json.enc -out tests/testthat/auth.json -d
