language: r
sudo: false
cache: packages
r_packages:
- knitr
- covr
- drat
after_success:
- Rscript -e 'library("covr");codecov()'
- test $TRAVIS_PULL_REQUEST == "false" && test $TRAVIS_BRANCH == "master" && bash
  drat.sh
env:
  global:
  - secure: GTRaJS+rNBDy8NkPvL47ey9XXkTWHPzTWvME8NofUjJWqcF2XynHlswE+U0N4rpO1NMjGbKBFDXblgJTQ8V5NiT9vORWTjKKhIMGVvKrsV95Wgl9tjLQj+1/Ughb3UU3OYvyHJXRxuiFzxrEfMdAJSnkvX7n1rWBbd1VJDgbFoBGmopY+Iq/wSo/ZIjhRuDR19tiB7C1OrOtVbd0Kzx0cSjCM/bZce40AXRuOerntblJExqTb9F9CGu4cfFfxamsThSnED+z8R6HKUlrwYb3us40vIea8O8Sh3TavTLU0hKQn1ZldzxqbUMUGKrbhcf+iwd2lt6RC9DvNdIqnI2HzeCw8nWZMUh4lS3GmTVFwiHY3BF+YrXPkRGwAh1JN2b5GsBeCgiSJwjBgOmBYJKPDiHsWZWuScxXEbe4L2xWsa9m1spkkTYTNraJlRicVwTaCeY/ObmH81s2SdaIwa9oGoZ4TuKZm30/c5JkD7tEcU+9P6xtcmT8/fEFy6Z8pVTPcrK77gesDl/nEJI65/8FVzRo1/+OevgNH4fcTdmuLNqpVL9a7U1AluxUJGGF2kwPSLbdISYY/DACykzN1e4SYGc0Lj+Gi5euFp8nPXrUh/5aaVoXy7cUH0wp4fGyIVlbygg864MUQWeuLxfJLqPevHrBj0ZGJKa0c0LVrNA6ywE=
  - secure: rQjEaSATmHSnEBaHH2lx+VpibJhVUBMH+ZsVuFqV00L64nKHHmWEirnqKPNEjJuPQoj+xE+FyBfiGKRaaWDRTxEb52nTe5Y/9Er6Rc/25/18hUh0sebCURu3M49/jlW1lvdAzXHNKKJq67tsJopK4LlmVeHsz/mlAIiZVHaSXVDCAZEOebpDuoAsOvg1Ap1ggDYYel2p+zpZcygwNpZ0w2L6jM8EoRCtTDft1Rplq6boJk6pXCa3rboyarJVWJUq2kZv8Sw0XwkcjxeYsWS/2ncnbDloQIJTgGe4cbzIONHtPTVrPTSnxBGyLMo0MmTkN9xy1+kpQrYw6dW1jwpFl5QDNPb1+ZmHh/tFnRkMgGFkvx2W3N2QGG2n9Yh7MdoRkVxnP52+KvR/nt259FG5VFPJZFF/h+CsZI710VhwGay2v3yH/qj46QJvnw2DPMdiE4h2rV19Ry0KLnV9iqgJnqceWBofaPj93Ybb320Nu30PrZaq6bm3VLpDWjTbEkbo+xNp8YrJZOfD9YaE7TFXIlSQmSEwtLGZwks7RscQtd/sjZpfaOomoZs5D4tVHkattL71XFKbPWh5kYicTzBMfO6xbAT8WEHg3qevQteFJH7dAwF7Af7U0fK4fOEkkApEtzbjYhAqkX2q2CWV9G/nREfNPiMbL6Xbu9RH6VEnwyM=
before_install:
- openssl aes-256-cbc -K $encrypted_d4ad93fbc68d_key -iv $encrypted_d4ad93fbc68d_iv
  -in auth.json.enc -out auth.json -d
